spring.application.name=salesflow


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
#server.port=8081



spring.jpa.show-sql=true

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#spring.datasource.url=jdbc:mysql://localhost:3306/db_sb_example
#spring.datasource.username=DefaultUser
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Hibernate / JPA
#spring.jpa.hibernate.ddl-auto=update